"""add snapshot + encryption tables

Revision ID: 66b8514f2f37
Revises: 0e529e9dbeae
Create Date: 2026-04-17 17:22:23.249811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b8514f2f37'
down_revision: Union[str, Sequence[str], None] = '0e529e9dbeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_encryption_keys',
    sa.Column('kid', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('wrap_algo', sa.String(length=32), nullable=False),
    sa.Column('kek_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kid')
    )
    op.create_index(op.f('ix_account_encryption_keys_account_id'), 'account_encryption_keys', ['account_id'], unique=False)
    op.create_table('device_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('payload_blob', sa.LargeBinary(), nullable=True),
    sa.Column('blob_uri', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('parent_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('compression', sa.String(length=8), nullable=True),
    sa.Column('encryption_kid', sa.String(length=64), nullable=True),
    sa.Column('created_by_ip', sa.String(length=45), nullable=True),
    sa.CheckConstraint("kind IN ('auto','manual','pre_restore','import')", name='ck_snapshot_kind'),
    sa.CheckConstraint('(CASE WHEN payload_json IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN payload_blob IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN blob_uri IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_snapshot_exactly_one_storage'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['device_configs.device_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_snapshot_id'], ['device_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_snapshots_account_id'), 'device_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_device_snapshots_parent_snapshot_id'), 'device_snapshots', ['parent_snapshot_id'], unique=False)
    op.create_index('ix_snap_account_kind_created', 'device_snapshots', ['account_id', 'kind', 'created_at'], unique=False)
    op.create_index('ix_snap_device_created', 'device_snapshots', ['device_id', 'created_at'], unique=False)
    op.create_table('snapshot_retention_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('keep_last_n_auto', sa.SmallInteger(), nullable=False),
    sa.Column('auto_expire_days', sa.SmallInteger(), nullable=True),
    sa.Column('keep_labeled_forever', sa.Boolean(), nullable=False),
    sa.Column('max_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['device_configs.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'device_id', name='uq_retention_scope')
    )
    op.create_index(op.f('ix_snapshot_retention_policies_account_id'), 'snapshot_retention_policies', ['account_id'], unique=False)
    op.create_table('device_heads',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('current_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['device_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['device_configs.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('snapshot_exports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['device_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_exports_account_id'), 'snapshot_exports', ['account_id'], unique=False)
    op.create_index(op.f('ix_snapshot_exports_created_at'), 'snapshot_exports', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_exports_created_at'), table_name='snapshot_exports')
    op.drop_index(op.f('ix_snapshot_exports_account_id'), table_name='snapshot_exports')
    op.drop_table('snapshot_exports')
    op.drop_table('device_heads')
    op.drop_index(op.f('ix_snapshot_retention_policies_account_id'), table_name='snapshot_retention_policies')
    op.drop_table('snapshot_retention_policies')
    op.drop_index('ix_snap_device_created', table_name='device_snapshots')
    op.drop_index('ix_snap_account_kind_created', table_name='device_snapshots')
    op.drop_index(op.f('ix_device_snapshots_parent_snapshot_id'), table_name='device_snapshots')
    op.drop_index(op.f('ix_device_snapshots_account_id'), table_name='device_snapshots')
    op.drop_table('device_snapshots')
    op.drop_index(op.f('ix_account_encryption_keys_account_id'), table_name='account_encryption_keys')
    op.drop_table('account_encryption_keys')
    # ### end Alembic commands ###
