"""add global_policies singleton

Revision ID: f84aaace640f
Revises: ef0bfac314bd
Create Date: 2026-04-17 17:13:40.441590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84aaace640f'
down_revision: Union[str, Sequence[str], None] = 'ef0bfac314bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_keep_last_n', sa.Integer(), nullable=False),
    sa.Column('snapshot_retain_days', sa.Integer(), nullable=False),
    sa.Column('max_bytes_per_user', sa.Integer(), nullable=True),
    sa.Column('registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_role', sa.String(length=16), nullable=False),
    sa.Column('banner_message', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_policies')
    # ### end Alembic commands ###
